reviews:

  path_instructions:
     - path: "src/**/*.sh"
      instructions: |
        These are shell module files that are sourced by the main script.
        - Proper variable quoting
        - Portable shell features
        - Security considerations
        - Error handling patterns
