reviews:
  path_instructions:
    - path: "src/**/*.sh"
      instructions: "These are shell module files that are sourced by the main script." 
        Shell script review:
        - Use 'set -euo pipefail' for safety
        - Proper variable quoting
        - Portable shell features
        - Security considerations
        - Error handling patterns
