reviews:
  path_instructions:
    - path: "src/**/*.sh"
      instructions: |
        Shell script review:
        - Use 'set -euo pipefail' for safety
        - Proper variable quoting
        - Portable shell features
        - Security considerations
        - Error handling patterns