name: Ensure Copilot Review on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  copilot-review-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Copilot review
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = context.payload.pull_request.number;
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            const copilotReviewed = reviews.some(
              review => review.user && review.user.login === 'github-copilot[bot]'
            );
            if (!copilotReviewed) {
              core.setFailed('Copilot has not reviewed this PR yet.');
            } else {
              core.info('Copilot review found.');
            }