name: 00 Review Staging

on:
  push:
    paths:
      - 'tools/stub_missing_staging.sh'
      - 'staging/test_*.sh'
      - '.github/workflows/test-stubs.yml'
      - '**.sh'
  pull_request:
    paths:
      - 'tools/stub_missing_staging.sh'
      - 'staging/test_*.sh'
      - '.github/workflows/test-stubs.yml'
      - '**.sh'

jobs:
  stub-and-test:
    name: "Test and stub missing"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set execute permissions
        run: |
          chmod +x ./tools/stub_missing_staging.sh
          chmod +x ./staging/test_*.sh || true

      - name: Run stub_missing_staging.sh
        run: ./tools/stub_missing_staging.sh

      - name: Run all test_*.sh scripts in staging/
        run: |
          for test_script in ./staging/test_*.sh; do
            shopt -s nullglob
            if [ -x "$test_script" ]; then
              echo "Running $test_script"
              "$test_script"
            else
              echo "Skipping $test_script (not executable)"
            fi
          done