name: ClamAV Scan

on:
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

jobs:
  clamav:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ClamAV
        run: sudo apt-get update && sudo apt-get install -y clamav
      - name: Update ClamAV database
        run: sudo freshclam
      - name: Scan for viruses
        run: clamscan -r --bell -i .