name: Run Testing Scripts

on:
  push:
    paths:
      - 'testing/**'
  pull_request:
    paths:
      - 'testing/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make setup and test scripts executable
        run: chmod +x ./testing/*

      - name: Run assemble_src.sh
        run: ./tools/assemble_src.sh

      - name: Run assemble_array.sh
        run: ./tools/assemble_array.sh

      - name: Run all test scripts in ./testing
        run: |
          set -e
          for script in ./testing/*; do
            # Skip the setup scripts to avoid running them again
            case "$script" in
              *assemble_src.sh|*assemble_array.sh) continue ;;
            esac
            if [ -f "$script" ] && [ -x "$script" ]; then
              echo "Running $script"
              "$script"
            fi
          done