name: Run Testing Scripts

on:
  push:
    paths:
      - 'testing/**'
  pull_request:
    paths:
      - 'testing/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make test scripts executable
        run: chmod +x ./testing/*

      - name: Run all test scripts in ./testing
        run: |
          set -e
          for script in ./testing/*; do
            if [ -f "$script" ] && [ -x "$script" ]; then
              echo "Running $script"
              "$script"
            fi
          done